coffee_bar_reviews/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf import settings
from django.views.static import serve

urlpatterns = [
    path('reviews/', include('reviews.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += [
        url(r'^media/(?P<path>.*)$', serve, {
            'document_root': settings.MEDIA_ROOT,
        })
    ]

reviews/urls.py
from django.urls import path

from .views import coffee_bars_detail, coffee_bars_list_view, register_view, login_view, logout_view

app_name = 'reviews'
urlpatterns = [
    path('', coffee_bars_list_view, name='home'),
    path('<int:coffee_bar_id>/', coffee_bars_detail, name='detail'),
    path('register', register_view, name='register'),
    path('login', login_view, name='login'),
    path('logout', logout_view, name='logout'),
]
   

reviews/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    first_name = models.CharField(max_length=255)
    last_name = models.CharField(max_length=255)
    phone = models.CharField(max_length=20, null=True)


class CoffeeBar(models.Model):
    name = models.CharField(max_length=255)
    summary = models.TextField(null=True)
    description = models.TextField()
    address = models.TextField(blank=False, null=False)
    image = models.ImageField(upload_to="coffee_bars", null=True)
    avg_vote = models.DecimalField(max_digits=3, decimal_places=1, default=0)
    created_at = models.DateTimeField(auto_now_add=True)

class Menu(models.Model):
    coffee_bar = models.ForeignKey(CoffeeBar, on_delete=models.CASCADE)
    name = models.CharField(null=False, blank=False, max_length=255)
    price = models.DecimalField(max_digits=10, decimal_places=0)
    image = models.ImageField(upload_to='menus', null=True, blank=True)
    description = models.CharField(null=True, max_length=255, blank=True)


class Review(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    coffee_bar = models.ForeignKey(CoffeeBar, on_delete=models.CASCADE)
    vote = models.PositiveIntegerField(default=5)
    description = models.TextField(null=True)
    created_at = models.DateTimeField(auto_now_add=True)

reviews/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2',)

    def clean_email(self):
        data = self.cleaned_data['email']
        if User.objects.filter(email=data).exists():
            raise forms.ValidationError("This email already used")
        return data


class ReviewForm(forms.Form):
    CHOICES = (
        (1, "1 star"),
        (2, "2 stars"),
        (3, "3 stars"),
        (4, "4 stars"),
        (5, "5 stars"),
    )
    rating = forms.ChoiceField(label='Vote', choices=CHOICES, initial=5)
    description = forms.CharField(label='Comment', required=False, widget=forms.Textarea())

    def clean_description(self):
        data = self.cleaned_data['description']
        if not data:
            raise forms.ValidationError("Your review is required")
        return data

reviews/views.py
from django.contrib.auth import login, authenticate, logout
from django.http.response import Http404
from django.shortcuts import render, redirect, get_object_or_404
from .models import CoffeeBar, Review
from .forms import SignUpForm, ReviewForm
from django.contrib.auth.forms import AuthenticationForm
from django.views import generic
from django.utils import timezone


# coffee bars list view
def coffee_bars_list_view(request):
    coffee_bars = CoffeeBar.objects.order_by("-avg_vote")[:10]
    context = {
        "list": coffee_bars,
        "auth": request.user,
    }
    return render(request, 'reviews/coffee_bars.html', context)


# coffee bars detail
def coffee_bars_detail(request, coffee_bar_id):
    coffee_bar = get_object_or_404(CoffeeBar, pk=coffee_bar_id)
    reviews = Review.objects.filter(coffee_bar__id=coffee_bar_id)
    if request.method == 'POST':
        form = ReviewForm(request.POST)
        if form.is_valid():
            description = form.cleaned_data['description']
            rating = form.cleaned_data['rating']
            r = Review(author=request.user, coffee_bar=coffee_bar, vote=rating, description=description)
            r.save()
            count = 0
            voted = 0
            for review in reviews:
                voted += review.vote
                count += 1
            coffee_bar.avg_vote = round((voted / count), 1)
            coffee_bar.save()

    else:
        form = ReviewForm()

    context = {
        'coffee_bar': coffee_bar,
        'reviews': reviews,
        "auth": request.user,
        "form": form
    }
    return render(request, 'reviews/coffee_bars_detail.html', context)


# register view
def register_view(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)
            login(request, user)
            return redirect('/reviews')
    else:
        form = SignUpForm()
    return render(request, 'reviews/register.html', {'form': form})


# Login view
def login_view(request):
    if request.method == 'POST':
        form = AuthenticationForm(request, data=request.POST)
        if form.is_valid():
            login(request, form.user_cache)
            return redirect('/reviews')
    else:
        form = AuthenticationForm()
    return render(request, 'reviews/login.html', {'form': form})


# Logout view
def logout_view(request):
    logout(request)
    return redirect('/reviews')

reviews/templates/base.html
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Coffee bars reviews</title>
    {% comment %} <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.2/css/bulma.min.css"> {% endcomment %}
</head>
<body>
<section class="header">
    <nav class="bd-navbar navbar is-light" role="navigation" aria-label="main navigation">
        <div class="container">
            <div class="navbar-brand">
                <a class="navbar-item" href="{% url 'reviews:home' %}">
                    <p class="title">Coffee Reviews</p>
                </a>
                <a role="button" class="navbar-burger" aria-label="menu" aria-expanded="false"
                   data-target="navbarBasicExample">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a>
            </div>
            <div id="navbarBasicExample" class="navbar-menu">
                <div class="navbar-start">
                    <a class="navbar-item" href="{% url 'reviews:home' %}">
                        All coffee bars
                    </a>
                </div>
                <div class="navbar-end">
                    <div class="navbar-item">
                        {% if auth.is_authenticated %}
                            <div class="buttons">
                                <a class="button is-light is-link is-small">
                                    <strong>{{ auth.first_name }} {{ auth.last_name }}</strong>
                                </a>
                                <a class="button is-primary is-small" href="{% url 'reviews:logout' %}">
                                    Sign out
                                </a>
                            </div>
                        {% else %}
                            <div class="buttons">
                                <a class="button is-primary is-small" href="{% url 'reviews:register' %}">
                                    <strong>Sign up</strong>
                                </a>
                                <a class="button is-light is-small" href="{% url 'reviews:login' %}">
                                    Log in
                                </a>
                            </div>
                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </nav>
    </div>
</section>
<section class="section">
    <div class="container">
        {% block content %}
        {% endblock %}
    </div>
</section>
</body>
</html>

reviews/templates/reviews/coffee_bars.html
{% comment %} {% extends 'base.html' %} {% endcomment %}

{% load static %}

{% block head %}
<!--    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">-->
    <link rel="stylesheet" type="text/css" href="{% static 'reviews/style.css' %}">
    <link href="{% static 'reviews/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'reviews/assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'reviews/assets/css/templatemo-sixteen.css' %}">
    <link rel="stylesheet" href="assets/css/owl.css">

    <header class="">
      <nav class="navbar navbar-expand-lg">
        <div class="container">
            <a class="navbar-brand"><h2>Coffee Bar Review</h2></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'reviews:home' %}">Home</a>
                </li> 
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'reviews:home' %}">All Coffee Bars</a>
                </li>
                {% if auth.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link"><strong>{{ auth.first_name }} {{ auth.last_name }}</strong></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'reviews:logout' %}">Sign out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'reviews:register' %}"><strong>Sign up</strong></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'reviews:login' %}">Log in</a>
                    </li>
                {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </header>
    
{% endblock head %}



{% block content %}
    {% if list %}
        <div class="reviews">
            <br><br><br><br>
            {% for coffeeBar in list %}
            <div class="cont shadow-2xl bg-white rounded-md mb-5 px-4 py-4">
                <div class="coffee-img">
                    <img class="img-item" src="{{ coffeeBar.image.url }}" width="200px" height="auto">
                </div>
                <div>
                    <h2>
                        <a href="{% url 'reviews:detail' coffeeBar.id %}">{{ coffeeBar.name }}</a>
                        <br>
                    </h2> 
                    <div class="coffee-bar-info">
                        <p class="address">Địa chỉ: {{ coffeeBar.address }}</p>
                        <p class="vote">Đánh giá: {{ coffeeBar.avg_vote }}</p>
                        <p class="summary">{{ coffeeBar.summary }}</p>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>

    {% else %}
        <p>Không có quán cafe nào.</p>
    {% endif %}
{% endblock %}

reviews/templates/reviews/coffee_bars_detail.html
{% comment %} {% extends 'base.html' %} {% endcomment %}


{% load static %}

{% block head %}
<!--    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">-->
    <link rel="stylesheet" type="text/css" href="{% static 'reviews/style.css' %}">
    <link href="{% static 'reviews/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'reviews/assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'reviews/assets/css/templatemo-sixteen.css' %}">
    <link rel="stylesheet" href="assets/css/owl.css">

    <header class="">
      <nav class="navbar navbar-expand-lg">
        <div class="container">
          <a class="navbar-brand"><h2>{{ coffee_bar.name }}</h2></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item active">
                <a class="nav-link" href="{% url 'reviews:home' %}">Home</a>
              </li> 
              <li class="nav-item">
                <a class="nav-link" href="#about_id">About Us</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#menu_id">Menu</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#review_id">Review</a>
              </li>
              <li class="nav-item">
                <a class="nav-link" href="#vote_id">Vote</a>
              </li>
              {% if auth.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link"><strong>{{ auth.first_name }} {{ auth.last_name }}</strong></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'reviews:logout' %}">Sign out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'reviews:register' %}"><strong>Sign up</strong></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'reviews:login' %}">Log in</a>
                    </li>
                {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </header>
    
{% endblock head %}



{% block content %}
<div>
    <h1>{{ coffee_bar.name }}</h1><br>
</div>


<div id="about_id" class="shadow-2xl bg-white rounded-md mb-5 px-4 py-4">
	<div >
		<p class="address">Địa chỉ: {{ coffee_bar.address }}</p>
		<p class="vote">Đánh giá: <strong>{{ coffee_bar.avg_vote }}</strong></p>
		<p class="coffee-bar-description">{{ coffee_bar.description }}</p>
	</div>
</div>


 <div id="menu_id" class="shadow-2xl bg-white rounded-md mb-5 px-4 py-4">
	<h1 class="text-black font-bold">Menu</h1>
		{% csrf_token %}
		{% for menu in coffee_bar.menu_set.all %}
		<div class="item">
			<div class="coffee-img">
            <img class="img-item" src="{{ menu.image.url }}" width="150px" height="auto">
			</div>
			<div class="item_menu">
				<label class="name" for="menu{{ forloop.counter }}">{{ menu.name }}</label>
				<label class="description" for="menu{{ forloop.counter }}">{{ menu.description }}</label>
				<label class="price" for="menu{{ forloop.counter }}">{{ menu.price }}đ</label>
			</div>
		</div>
		{% endfor %}

</div>


<div id="review_id" class="shadow-2xl bg-white rounded-md mb-5 px-4 py-4">
	<h1 class="text-black font-bold">Review</h1>
		{% csrf_token %}
		{% if reviews %}
			{% for review in reviews %}
				<div class="item">
					<label class="user-name" for="review{{ forloop.counter }}">{{ review.author.last_name }} {{ review.author.first_name }}</label>
					<label class="vote" for="review{{ forloop.counter }}">{{ review.vote }} sao</label>
					<label class="description" for="review{{ forloop.counter }}">{{ review.description }}</label>
					<label class="time" for="review{{ forloop.counter }}">{{ review.created_at }}</label>
				</div>
			{% endfor %}
		{% else %}
        	<p>There aren't any review.</p>
    {% endif %}
</div>

 {% if auth.is_authenticated %}
<div id="vote_id" class="shadow-2xl bg-white rounded-md mb-5 px-4 py-4">
<h1 class="text-black font-bold">Vote</h1>
	{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
	<form method="post">
        {% csrf_token %}
        {% if form.errors %}
            <div class="notification is-danger">
                <ul>
                    {% for key, value in form.errors.items %}

                        <li>
                            {{ value }}
                        </li>

                    {% endfor %}
                </ul>
            </div>
        {% endif %}
        {% for field in form %}
            <div>
                <label>
                    {{ field.label_tag }}
                </label>
                <div >
                    {{ field }}
                </div>
                {% if field.help_text %}
                    <p>{{ field.help_text }}</p>
                {% endif %}
                {% for error in field.errors %}
                    <p>{{ error }}</p>
                {% endfor %}
            </div>
            <br>
        {% endfor %}
        <div>
            <div>
                <button class="btn" type="submit">Send review</button>
            </div>
        </div>
    </form>
</div>
{% else %}
<p><a href="{% url 'reviews:login' %}">Login</a> to review.
</p>
{% endif %}

{% endblock content %}

reviews/templates/reviews/login.html
{% load static %}

{% block head %}
<!--    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">-->
    <link rel="stylesheet" type="text/css" href="{% static 'reviews/style.css' %}">
    <link href="{% static 'reviews/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'reviews/assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'reviews/assets/css/templatemo-sixteen.css' %}">
    <link rel="stylesheet" href="assets/css/owl.css">

    <header class="">
      <nav class="navbar navbar-expand-lg">
        <div class="container">
            <a class="navbar-brand"><h2>Coffee Bar Review</h2></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'reviews:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'reviews:home' %}">All Coffee Bars</a>
                </li>
                {% if auth.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link"><strong>{{ auth.first_name }} {{ auth.last_name }}</strong></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'reviews:logout' %}">Sign out</a>
                    </li>
                {% else %}

                 <li class="nav-item">
                        <a class="nav-link" href="{% url 'reviews:register' %}"><strong>Sign up</strong></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'reviews:login' %}">Log in</a>
                    </li>


                {% endif %}
            </ul>
          </div>

        </div>
      </nav>
    </header>

{% endblock head %}


{% block content %}
    <h1 class="title">Sign In</h1>
    <form method="post">
        {% csrf_token %}
        {% if form.errors %}
            <div class="notification is-danger">
                <ul>
                    {% for key, value in form.errors.items %}

                        <li>
                            {{ value }}
                        </li>

                    {% endfor %}
                </ul>
            </div>
        {% endif %}
        {% for field in form %}
        <div class="login-form">
            <div class="">
                <div class="login-field">
                <label id="id_username" class="label is-small">
                    {{ field.label_tag }}
                </label>
                <div class="control">
                    {{ field }}
                </div>
                {% if field.help_text %}
                    <p class="help">{{ field.help_text }}</p>
                {% endif %}
                {% for error in field.errors %}
                    <p class="help is-danger">{{ error }}</p>
                {% endfor %}

             </div>
           </div>
        {% endfor %}
            <div class="field is-grouped">
                <div class="control">
                <button type="submit" id="btn" class="btn button is-primary is-small">Sign In</button>
                </div>
            </div>
        </div>
    </form>
{% endblock %}

reviews/templates/reviews/register.html
{% load static %}

{% block head %}
<!--    <link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900&display=swap" rel="stylesheet">-->
    <link rel="stylesheet" type="text/css" href="{% static 'reviews/style.css' %}">
    <link href="{% static 'reviews/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'reviews/assets/css/fontawesome.css' %}">
    <link rel="stylesheet" href="{% static 'reviews/assets/css/templatemo-sixteen.css' %}">
    <link rel="stylesheet" href="assets/css/owl.css">

    <header class="">
      <nav class="navbar navbar-expand-lg">
        <div class="container">
            <a class="navbar-brand"><h2>Coffee Bar Review</h2></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarResponsive">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'reviews:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'reviews:home' %}">All Coffee Bars</a>
                </li>
                {% if auth.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link"><strong>{{ auth.first_name }} {{ auth.last_name }}</strong></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'reviews:logout' %}">Sign out</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'reviews:register' %}"><strong>Sign up</strong></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'reviews:login' %}">Log in</a>
                    </li>
                {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </header>

{% endblock head %}


{% block content %}
    <h1 class="title">Create an account</h1>
    <form method="post">
        {% csrf_token %}
        {% if form.errors %}
            <div class="notification is-danger">
                <ul>
                    {% for key, value in form.errors.items %}

                        <li>
                            {{ value }}
                        </li>

                    {% endfor %}
                </ul>
            </div>
        {% endif %}
        {% for field in form %}
        <div class="login-form ">

            <div class="register-form field">
<!--                field-->
<!--                <label class="label is-small">-->
<!--                    {{ field.label_tag }}-->
<!--                </label>-->
<!--                <div class="control" id="aaa">-->
<!--                    {{ field }}-->
<!--                </div>-->
                <div class="register-required">
                                    <label class="label is-small">
                    {{ field.label_tag }}
                </label>
                <div class="control" id="aaa">
                    {{ field }}
                </div>
                </div>
                {% if field.help_text %}
                    <p class="help">{{ field.help_text }}</p>
                {% endif %}
                {% for error in field.errors %}
                    <p class="help is-danger li">{{ error }}</p>
                {% endfor %}

        </div>
        {% endfor %}
        <div class="field is-grouped">
            <div class="control">
                <button type="submit" id="btn" class="btn button is-primary is-small">Create an account</button>
            </div>
        </div>
        </div>
    </form>
{% endblock %}